"""Initial Supabase PostgreSQL migration

Revision ID: 1dd7f310902a
Revises: 
Create Date: 2026-06-09 15:12:07.259315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd7f310902a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('context_filters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workbooks_filename'), 'workbooks', ['filename'], unique=False)
    op.create_table('batch_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('enrollments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('rank_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copilot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['copilot_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('collection', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executive_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leader_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('leader_name', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offering_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workbook_id', sa.UUID(), nullable=False),
    sa.Column('offering', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offering_performance')
    op.drop_table('leader_performance')
    op.drop_table('executive_summary')
    op.drop_table('daily_performance')
    op.drop_table('copilot_messages')
    op.drop_table('category_performance')
    op.drop_table('batch_performance')
    op.drop_index(op.f('ix_workbooks_filename'), table_name='workbooks')
    op.drop_table('workbooks')
    op.drop_table('copilot_sessions')
    # ### end Alembic commands ###
